### ISSUE TITLE
RC version is failing

### ISSUE THREAD

**Issue by caioquirino** [eisengrind/docker-altv-server#11]
Hey, thanks for the awesome work! I liked the way you are downloading everything directly and keeping it up-to-date! :)

I have tried to run using the rc version and got the following error:

docker-compose.yml:
```
➜ cat docker-compose.yml
version: "3.9"
services:
  altv:
    image: eisengrind/altv-server:rc
    ports:
      - "7788:7788"
    volumes:
      - ./server.cfg:/opt/altv/server.cfg
 ```

➜ docker-compose up
Pulling altv (eisengrind/altv-server:rc)...
rc: Pulling from eisengrind/altv-server
f7ec5a41d630: Pull complete
df008b936927: Pull complete
00f3446bfa0a: Pull complete
951828b0298a: Pull complete
1d366a381e89: Pull complete
Digest: sha256:0a7a854c4fbb2ebaf5a75e4998f229434fb06f728e574d5d220ad817ab457a9a
Status: Downloaded newer image for eisengrind/altv-server:rc
Recreating altv_br_eu_altv_1 ... done
Attaching to altv_br_eu_altv_1
altv_1  | [13:45:39] alt:V Server 3.0-rc6 (rc)
altv_1  | [13:45:39] Starting Alt:V Server on Docker! on 0.0.0.0:7788
**altv_1  | [13:45:39][Error] Failed to load module "/opt/altv/modules/libcsharp-module.so"
altv_1  | 	 Module outdated, module uses SDK v48, server requires SDK v52**
altv_1  | [13:45:39] Required server permissions:
altv_1  | [13:45:39] Optional server permissions:
altv_1  | [13:45:39] Starting HTTP server on 0.0.0.0:7788
altv_1  | [13:45:39] Main thread started (ThreadId: 9)
altv_1  | [13:45:39] Colshape thread started (ThreadId: 10)
altv_1  | [13:45:39] EntityStreamer thread started (ThreadId: 18)
altv_1  | [13:45:39] Server started

**Comment by pixlcrashr** [comment]
I'll get into it asap

**Comment by caioquirino** [comment]
Thank you @TheMysteriousVincent ! I have tried also with the release and it is also failing.

docker-compose:
```
version: "3.9"
services:
  altv:
    image: eisengrind/altv-server:release
    ports:
      - 7788:7788
    environment:
      - ALTV_VOICE_SERVER_SECRET=123456789

  altv_voice:
    image: eisengrind/altv-voice-server:release
    ports:
      - 7798:7798
      - 7799:7799
```

log:

```
Creating altv_br_eu_altv_voice_1 ... done
Creating altv_br_eu_altv_1       ... done
Attaching to altv_br_eu_altv_1, altv_br_eu_altv_voice_1
altv_1        | [16:55:21] alt:V Server 2.23 (release)
altv_1        | [16:55:21] Starting Alt:V Server on Docker! on 0.0.0.0:7788
altv_1        | [16:55:21] coreclr-module: version found: 5.0.5
altv_1        | [16:55:21] coreclr-module: version found: 3.1.13
altv_1        | [16:55:21] coreclr-module: greatest version: 5.0.5
altv_1        | [16:55:21] Required server permissions:
altv_1        | [16:55:21] Optional server permissions:
altv_1        | [16:55:21] Starting HTTP server on 0.0.0.0:7788
altv_1        | [16:55:21] Main thread started (ThreadId: 9)
altv_1        | [16:55:21] Colshape thread started (ThreadId: 10)
altv_1        | [16:55:21] EntityStreamer thread started (ThreadId: 23)
altv_1        | [16:55:21] Network thread started (ThreadId: 25)
altv_1        | [16:55:21] Server started
altv_1        | Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
altv_1        | File name: 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
altv_1        | 
altv_1        | 
altv_1        | /root/entrypoint.sh: line 150:     9 Aborted                 ./altv-server --config=/opt/altv/server.cfg $ALTV_SERVER_LOG_PATH $ALTV_SERVER_NO_LOGFILE
```
