### ISSUE TITLE
No such file or directory /root/entrypoint.sh

### ISSUE THREAD

**Issue by ZackaryH8** [eisengrind/docker-altv-server#28]
When I run the following compose, I get this in the console. any ideas why?

## Compose
```yaml
---
version: '3.8'
services:
    altv:
        image: eisengrind/altv-server:js-dev
        container_name: altv
        environment:
            - ALTV_SERVER_NAME=Test Server
            - ALTV_SERVER_PORT=7788
            - ALTV_SERVER_PLAYERS=10
            - ALTV_SERVER_PASSWORD=MyPass
            - ALTV_SERVER_ANNOUNCE=false
            - ALTV_SERVER_LANGUAGE=en
            - ALTV_SERVER_DESCRIPTION=testing server
            - ALTV_SERVER_MODULES=js-module
            - ALTV_SERVER_RESOURCES=boilerplate
            - ALTV_SERVER_DEBUG=true
        ports:
            - '7788:7788/tcp'
            - '7788:7788/udp'
        volumes:
            - /home/ubuntu/rebelRoleplay:/opt/altv
        privileged: true
        restart: unless-stopped
```

## Console
```
/root/entrypoint.sh: line 149: ./altv-server: No such file or directory
/root/entrypoint.sh: line 149: ./altv-server: No such file or directory
/root/entrypoint.sh: line 149: ./altv-server: No such file or directory
```
